### ISSUE TITLE
Как?

### ISSUE THREAD

**Issue by Grinyaha** [Temus/elFinder#1]
Как это все в evo установить?

**Comment by Grinyaha** [comment]
Разобрался, надо переименовть browser.php в browse.php, исправь плиз.

**Comment by Temus** [comment]
Это в Evo Custom просто TinyMCE 4 жестко привязали к KCFinder и его файлу browse.php. На самом деле там должен быть browser.php, как и везде в других местах (tv image и т.п.). Добавил нужный файл, в нём немного другой код (просто переименовать нельзя - не будет работать выборка).
